version: '3.8'

services:
  django_gunicorn:
    volumes:
      - static:/static
    build:
      context: .
    image: joelgxp/fox-django:latest
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    image: joelgxp/fox-nginx:latest
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django_gunicorn

volumes:
  static:
