# Generated by Django 5.0.1 on 2024-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='vendido',
            field=models.BooleanField(default=0),
        ),
    ]
