# Generated by Django 5.0.1 on 2024-03-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('renavam', models.CharField(max_length=11)),
                ('chassi', models.CharField(max_length=45)),
                ('cor', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_fabricacao_modelo', models.IntegerField()),
                ('data_entrada', models.DateField()),
            ],
        ),
    ]
