# Generated by Django 5.0.1 on 2024-03-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
