# Generated by Django 5.0.1 on 2024-03-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_servico_tempo_execucao_alter_servico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='id_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.veiculo'),
        ),
    ]
