# Generated by Django 5.0.1 on 2024-03-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_servico_nome_alter_servico_tempo_execucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.IntegerField()),
                ('servicos', models.ManyToManyField(to='index.servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.veiculo')),
            ],
        ),
    ]
