# Generated by Django 5.0.1 on 2024-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_ordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aberta'), (1, 'Pendente'), (2, 'Concluída'), (3, 'Cancelada')], default=0),
        ),
    ]
