# Generated by Django 5.0.1 on 2024-03-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_ordemservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos',
        ),
    ]
