# Generated by Django 5.0.1 on 2024-03-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_ordemservico_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='id_veiculo',
        ),
    ]
