# Generated by Django 5.0.1 on 2024-03-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_ordemservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.AddField(
            model_name='servico',
            name='ordem_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.ordemservico'),
            preserve_default=False,
        ),
    ]
