# Generated by Django 5.0.1 on 2024-03-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_servico_ordem_servivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='ordem_servivo',
            new_name='ordem_servico',
        ),
    ]
