name: CI

on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}   
      
      - name: Build and push Docker images Django
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: | 
            joelgxp/fox-django:${{github.run_number}}
            joelgxp/fox-django:latest

      - name: Build and push Docker images Nginx
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: | 
            joelgxp/fox-nginx:${{github.run_number}}
            joelgxp/fox-nginx:latest

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
    - name: SSH and run Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          dir
          cd compose-fox
          docker pull joelgxp/fox-django:latest
          docker pull joelgxp/fox-nginx:latest
          docker-compose down
          docker-compose up -d
          docker image prune -f
        
          
